### ISSUE TITLE
Pipeline_annotations.py - Generation of geneses_all automatically excludes non-standard contigs

### ISSUE THREAD

**Issue by Charlie-George** [CGATOxford/CGATPipelines#118]
geneset_all.gtf.gz only contains chr 1-22 + XY even when there are no contigs set for removal in the pipeline ini. 

It would be useful to have the Mt genes and those on unknown contigs for some analysis but these get filtered because the UCSC and ensembl naming patterns do not match up. This is because gff2gff.py only adds "chr" before the chr id from the ensembl gff, where as the UCSC names are more complex. 

A more sophisticated regex should be able to fix this?

**Comment by AndreasHeger** [comment]
Thanks, the mitochondrial genes should be in there (as chrM).

The mapping between different chrosome names actually happens in IndexedFasta.py. IndexedFasta accepts a list of synonyms that can be added to the index, see for example:

```
chrUn_gl000248  2922440271      2922440287      39786
chrUn_gl000249  2922480074      2922480090      38502
chrX    2922518593      2922518599      155270560
chrY    3077789160      3077789166      59373566
chrM    chrMT
```

I would prefer explicit over implicit via a regex.
