### ISSUE TITLE
Backwards compatibility and changelogs

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#120]
I've recently noticed that the mapping classes no longer automatically pick up mapping options from the ini files, but require them to be explicitly passed when building the Mapper object. 

This seems to be contrary to the documentation, which states

```
When implementing a tool, avoid specifying algorithmic options as
class variables. Instead use an option string that can be set in
:file:`pipeline.ini`. *The only arguments to a tool constructor should
pertain to pipeline integration, such as filenames, index locations,
threading and in general processing options that change the tools
input/output, as these need to be tracked by the pipeline.*
```

More importantly, there used to be an expectation that when changes were made, old code would continue to function as before wherever possible. However, none of my code that uses Mapper objects works any more, worst still, the failure is silent: it runs without error, its just not using the options to the mapping tools. 

More generally, as our user base becomes more disperse, I think it is increasingly important that change-logs are kept where behavior of existing code changes.

**Comment by AndreasHeger** [comment]
Thanks, I think the statement still holds, which mapper do you refer to? For example, for bwa we have:

```
            bwa aln %%(bwa_aln_options)s -t %%(bwa_threads)i
            %(index_prefix)s %(infiles1)s
            > %(tmpdir)s/%(track1)s.sai 2>>%(outfile)s.bwa.log; checkpoint;
            bwa aln %%(bwa_aln_options)s -t %%(bwa_threads)i
            %(index_prefix)s %(infiles2)s
            > %(tmpdir)s/%(track2)s.sai 2>>%(outfile)s.bwa.log; checkpoint;
            bwa sampe %%(bwa_sampe_options)s %(index_prefix)s
                      %(tmpdir)s/%(track1)s.sai %(tmpdir)s/%(track2)s.sai
                      %(infiles1)s %(infiles2)s
            > %(tmpdir)s/%(track)s.sam 2>>%(outfile)s.bwa.log;
            ''' % locals())
```

I.e. bwa_aln_options and bwa_sampe_options will be inserted from the configuration file?

**Comment by IanSudbery** [comment]
Hi Andreas,

Hmmm… okay, this seems to be a bowtie specific problem. Which is odd,
because the tool_options parameter has been added to the Mapper class
**init**, but appears to only be used by the Bowtie class. Looks like
someone intended to change things over, but never got finished.

In Bowtie.mapper:

statement = '''

```
        %(executable)s --quiet

        --threads %%(bowtie_threads)i

        %(data_options)s

        %(tool_options)s

        %(index_option)s %(index_prefix)s

        %(infiles)s

        %(output_option)s

        2>%(outfile)s.log

        | awk -v OFS="\\t" '{sub(/\/[12]$/,"",$1);print}'

        | samtools import %%(reffile)s - %(tmpdir_fastq)s/out.bam

        1>&2 2>> %(outfile)s.log;

        ''' % locals()
```

Ian

_From:_ Andreas Heger [mailto:notifications@github.com]
_Sent:_ 09 November 2015 11:14
_To:_ CGATOxford/CGATPipelines
_Cc:_ Ian Sudbery
_Subject:_ Re: [CGATPipelines] Backwards compatibility and changelogs (#120)

Thanks, I think the statement still holds, which mapper do you refer to?
For example, for bwa we have:

```
        bwa aln %%(bwa_aln_options)s -t %%(bwa_threads)i

        %(index_prefix)s %(infiles1)s

        > %(tmpdir)s/%(track1)s.sai 2>>%(outfile)s.bwa.log; checkpoint;

        bwa aln %%(bwa_aln_options)s -t %%(bwa_threads)i

        %(index_prefix)s %(infiles2)s

        > %(tmpdir)s/%(track2)s.sai 2>>%(outfile)s.bwa.log; checkpoint;

        bwa sampe %%(bwa_sampe_options)s %(index_prefix)s

                  %(tmpdir)s/%(track1)s.sai %(tmpdir)s/%(track2)s.sai

                  %(infiles1)s %(infiles2)s

        > %(tmpdir)s/%(track)s.sam 2>>%(outfile)s.bwa.log;

        ''' % locals())
```

I.e. bwa_aln_options and bwa_sampe_options will be inserted from the
configuration file?

—
Reply to this email directly or view it on GitHub
https://github.com/CGATOxford/CGATPipelines/issues/120#issuecomment-155031048
.[image: Image removed by sender.]

**Comment by AndreasHeger** [comment]
Looks like this was me, I will revert this.

**Comment by Acribbs** [comment]
closed but please reopen if still an issue
