### ISSUE TITLE
Adding new pipelines

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#136]
Hi All,

I'd like to add my iCLIP and 4C pipelines from CGAT Projects 28 and 14 to the repository and integrate them with the testing framework. What do I need to do to do this? 

In addition both pipeline, but particularly the iCLIP one, come with quite a lot of accessory algorithmic code. This is both in the form of a general iCLIP module, and a specific  PipelineiCLIP module, as well as a number of standalone, but highly specialized scripts (such as `find_significant_bases.py` and `count_clip_sites.py` and `compare_clip_replicates.py`). These are sort of taking the place of external software like edgeR would in RNA-seq or MACS would in ChIP-seq, but which don't exist for 4C or iCLIP. 

Should these scripts go in the CGAT code collection? It seems a bit wrong putting them there because they are so specialized.

**Comment by AndreasHeger** [comment]
Hi Ian,

how about in the first instance adding them as a separate repository under the project name? See
for example the repository proj029 that Nick created.

Best wishes,
Andreas

**Comment by IanSudbery** [comment]
Sure. Sure repositories already exist, they are just not on github. I'll push them up, so that others can get access to the code.

**Comment by jscaber** [comment]
Dear Ian,
many thanks for that - I'd be very keen to start using that pipeline with some external iCLIP data that I want to compare to my existing RNAseq - let me know when you get round to pushing the repository.
Best wishes,
Jakub

**Comment by IanSudbery** [comment]
See new pipeline_iCLIP repository.

**Comment by Acribbs** [comment]
@IanSudbery @jscaber I assume this can be closed. please reopen if not
