### ISSUE TITLE
Modifiying temporary file name suffixes with P.getTempFilename()

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/CGATPipelines#159]
P.getTempFilename() currently generates temporary file names without suffixes. IOTools.openFile() uses the suffix to identify compressed files. The following therefore results in IOTools.openFile() failing to recognise that the file is compressed.

``` python
tmp = P.getTempFilename()

statement = "cat %(my_file)s | gzip > %(tmp)s "

P.run()

with IOTools.openFile(tmp, "r") as inf:
    ...
```

One can simply append the neccessary suffix to the temporary filename, e.g 

``` python
tmp = P.getTempFilename() + ".tmp"
```

but then the temporary file created by P.getTempFilename() is no longer being actually being used.

Suggest adding a suffix option to the various tempfile functions in Pipeline/Files.py. This can then be passed to tempfile.NamedTemporaryFile. Alternatively, IOTools.openFile() could accept a compression option?

**Comment by AndreasHeger** [comment]
Done, see c21f954
