### ISSUE TITLE
Problematic issue with generation of non-shared temporary files

### ISSUE THREAD

**Issue by snsansom** [CGATOxford/CGATPipelines#174]
Looking at P.getTempFilename() in CGATPipelines/Pipeline/File.py consider:
- A user runs a pipeline on head_node
- A "to_cluster=yes" task does "tmp_file = P.getTempFilename()"
- P.getTempFilename() will safely write a temporary file in PARAMS["tmpdir"] _on the head_node_! and return the name to the python variable.
- The job goes to the cluster
- The user will inadvertently write an unsafe (i.e. name collision possible) temporary file in PARAMS["tmpdir"] on a compute_node according the python variable set on the head_node.

There are then 2 temporary files which both need to be cleaned up - likely partly because of this there are e.g. quite a lot of files in /scratch on cgat150:

> stephens@cgat150:/ifs/home/stephens/
> $ ls /scratch/ | wc -l
> 179850`

More serious is if the files are cleaned up only on the head node - they will then remain on the compute node scratch: this will happen unless users explicitly rm the tmpfile in the job statement...

It seems clear that a python script executing on a head node cannot give a safe temporary filename for local scratch space on a compute node.

Furthermore, the arbitrary requirement to open a file of the same name on the head node prevents specification of the node scratch location in an environment variable by the queue manager (e.g. in a job prolog script).

To non-destructively fix I suggest:

(1) A new a PARAM["local_tmpdir"] variable that cluster jobs requiring a temporary filename can use to safely get a temporary file on the node, e.g. using the bash utility i.e. "mktemp" in the job statement i.e.

> statement='''tmpfile=`mktemp -p %(local_tmpdir)s`;
>                   cat my_data > $tmpfile;
>                   rm $tmpfile'''

(2) Moving forward use of PARAMS["tmpdir"] is depreciated and P.getTempFile() and P.getTempFilename() only use PARAMS["shared_tmpdir"] if a folder is not specified.

Note that this will also allow for specification of the compute node scratch space location via a shell environment variable so that queue managers can deploy and clean up scratch resources (i.e. PARAMS["local_tmpdir"] can then be set to contain the name of a shell environment variable.)

Can I please implement these changes?

**Comment by snsansom** [comment]
'local_tmpdir' added to CGATPipelines/Pipeline/Parameters.py.

See:
https://github.com/CGATOxford/CGATPipelines/commit/49dfd998e32728c1aa5c805e1d77e001158694b1

Note that PARAMS["local_tmpdir"] is intended to be directly passed to the job script as follows:

> statement = '''
> my_temp_file=`mktemp -p %(local_tmpdir)s`;
> # do stuff with $my_temp_file;
> rm $my_temp_file;
> '''
> P.run()

Please do not reference in task python code or portability will likely be broken!

I suggest depreciating use of PARAMS["tmpdir"] and re-writing existing code as above.

**Comment by AndreasHeger** [comment]
Hi @snsansom , I am not sure why local_tmpdir is required? This is exactly what tmpdir is!

Yes, the temporary file gets created on the head-node, but this means that within a CGAT environment, temporary files are unique across the cluster, which is an even stricter requirement
than being unique on a node. The `ctmp` prefix ensures that there is no conflict with other tools creating a temporary file.

Yes, clean-up could be improved, but I think the changes are unnecessary.

**Comment by snsansom** [comment]
The difference is that "local_tmpdir" is not meant to be evaluated on the head node.

In our setup, a SLURM prolog makes a per-job scratch dir on the execution node and sets it in an environment variable. It is necessary therefore to pass this straight through to the job statement in the way described above.

If I used "tmpdir" for this purpose i.e. PARAMS["tmpdir"]=$SCRATCH_DIR all existing references to P.getTempFile() will fail on the head node.

Also:
- Temporary files are not necessarily unique across the cluster by the current design - the head node ultimately has no way of knowing the contents of execution node /scratch.
- The current system lends itself to abuse - i.e. users pass a P.getTempFilename() var to a task and then do an os.unlink after P.run(): the tempfile is not deleted from the execution host.

EDIT: also note the exposure of the current design to name space collisions if people do not rm $tmpfile on the node but os.unlink() it on the head.

**Comment by AndreasHeger** [comment]
Thanks. Providing a job-specific tmp dir is a good solution and I see the need to feed the environment variable to job scripts.

I am worried that we now have two ways to use temp files. Does the following not work out-of
the box?

``` python
    statement = '''
    my_temp_file=`mktemp -p %(tmpdir)s`;
    # do stuff with $my_temp_file;
    rm $my_temp_file;
    '''
    P.run()
```

This would be the proper solution and new tasks should be written as such.

In the current solution, temporary names are all handled by the head-node, hence I would think that they are unique on each node as well? I don't see the way there would be a conflict unless intentionally creating one?  

Indeed, there is no principled solution for clearing up the temp files and people need to use the correct pattern in order to not have debris lying around.

**Comment by snsansom** [comment]
Thanks.

Your statement is correct for new pipelines, but all existing references to P.getTempFile() (and there are a lot in CGATPipelines!) would trip over when passed e.g. "$SCRATCH_DIR" on the head node*

Currently if a tmpfile is cleaned up the head node but not on the execution node (I am sure this happens frequently) are you not open to name space collision?

Here our solution for cleaning up node scratch is an accompanying SLURM epilog that does "rm -rf $SCRATCH_DIR". It seems to work nicely :).

(*I know because I did try this first :))

**Comment by AndreasHeger** [comment]
I see, I am getting there. Ok, let us do both.

> Currently if a tmpfile is cleaned up the head node but not on the execution node (I am sure this happens frequently) are you not open to name space collision?

If two pipelines are running concurrently, they will coordinate tempfiles via the head node and there should be no conflict. If one pipeline has finished, but failed to clean up, and another job by chance gets the same temporary filename, then the existing tmpfile will simply be overwritten, but nobody will be missing its contents.

I fully admit that this is not the best solution and providing per-job scratch is much cleaner.

**Comment by snsansom** [comment]
For reference this is the nub of the issue ($SCRATCH_DIR set and exported in bash):

`>>> tempfile.NamedTemporaryFile(dir="$SCRATCH_DIR")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gfs/apps/apps/python-2.7.11/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/gfs/apps/apps/python-2.7.11/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '$SCRATCH_DIR/tmp1c6SCo'
`

**Comment by snsansom** [comment]
Cool thanks for taking the time to go through it. If CGAT moves to SLURM I'll be happy to share our setup.
