### ISSUE TITLE
Adding Picard RnaSeqMetrics to Mapping Pipeline

### ISSUE THREAD

**Issue by jscaber** [CGATOxford/CGATPipelines#191]
While the RNASeqQC Pipeline provides a rough estimation of RNASeq biases, I thought it might be useful to implement the picard RNASeqQC metrics in the mapping pipeline, to give a more quantifiable/numerical assessment of biases that can then be used for downstream analysis. Please let me know if you support/object this addition, and I will start implementing it in a similar manner as other picard metrics are already handled.

**Comment by MikeDMorgan** [comment]
Given this is specific to RNAseq I suspect it would be better to implement this properly in the RNAseq QC pipeline, rather than introduce a protocol/method specfic task in to the generic mapping pipeline.

**Comment by TomSmithCGAT** [comment]
I'd agree except that we're only mapping a subset of reads so the Picard metrics will be very inaccurate. The mapping pipeline already performs some tasks only when using a spliced aligner so it wouldn't make it any less generic.

**Comment by jscaber** [comment]
I like that solution & it would does make sense to combine the picard tools in the already available MappingQC module. Making the function/method splice dependent might not cater for the few occasions where RNASeq is done on an unspliced genome? I'm open to both avenues.

**Comment by TomSmithCGAT** [comment]
I don't think the Picard tool is suitable when you have an unspliced genome. Many of the stats relate to intronic reads etc.

**Comment by jscaber** [comment]
May I make a change to the pipeline_mapping pipeline.ini?
The Picard RNASeqMetrics function requires information on strandedness. It would make sense to add this to the general options. We also have three mappers in the pipeline that require strandedness (hisat and tophat 1/2).
I would remove the strandedness option from the tool-specific options and add it to the pipeline.ini general options and populate all tools that use it from there.
To it would make sense to have just one option for strandedness, and I would use the HISAT nomenclature for the pipeline.ini. i.e. "RF", "FR" for paired-end, "F" and "R" for single-end. Default: none.

I am open to other suggestions.

**Comment by TomSmithCGAT** [comment]
This seems like a good idea to me.

The user would optionally provide strandedness under the "general" section and the mappers would take the strandedness parameter and convert it to the correct strandedness option. Is that right?

Take care with the tool specific strandedness options. They sometimes seem a bit backwards!

**Comment by jscaber** [comment]
They are indeed & I would appreciate someone checking the commit once it's ready.
I will put a also put a detailed explanation in the pipeline.ini.

**Comment by TomSmithCGAT** [comment]
Very happy to check (I'll need to re-read the relevant sections of the manuals again though!)

**Comment by Charlie-George** [comment]
Sounds great, it might be good to include this link in the ini as a reference - as it's by far the best explanation of the different libraries that I've come across. 
http://sailfish.readthedocs.org/en/master/library_type.html
