### ISSUE TITLE
Peakcalling class

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/CGATPipelines#198]
@MikeDMorgan . I've started building a peakcaller class. See 6695ab7. For testing purposes, I'm using the pipeline_peakcalling test data and hardcoding the infile, outfile in the pipeline (see `/ifs/home/toms/testing_area/peakcalling_scrum/test_peakcalling.dir`)

In the last meeting, Andreas suggested it would be best if the all the necessary code was run in a single statement(s) to keep it on a single node, hence, the Mapper class-like statement building. 

For now, the only peakcaller (Macs2) just calls peaks and compresses the outfiles. The postProcess method to parse the output to generate the generic output is currently empty. I note the current peakcalling pipeline uses `bed2table method==peak` - perhaps this script should be used throughout in order to generate the generic output?

**Comment by MikeDMorgan** [comment]
That all looks very reasonable.  If there is working code in the current peakcalling pipeline we can re-use then I think we should for the postProcess method.

**Comment by MikeDMorgan** [comment]
I can't see any major issues with the additional postprocessing.  I'm yet to test it though, I'l take a look when I'm in the office tomorrow.
