### ISSUE TITLE
pipeline_exome

### ISSUE THREAD

**Issue by logust79** [CGATOxford/CGATPipelines#204]
- Smart bam files merging (1 lane per sample doesn't need to spend time on merging)
- Optional bam indel realign (skip by default, as suggested by GATK best practice)
- Need to solve racing problem
- Optional hard filter for limited sample sizes (<30. Ideally sample-size aware)
- VQSR needs to be done before any annotations
- Add VEP to annotations

**Comment by Acribbs** [comment]
Was this enhancement made? I know that there are very few people still working on exosome pipeline

**Comment by Acribbs** [comment]
I will close this issue but please reopen if required
