### ISSUE TITLE
SCRUM - Annotations 

### ISSUE THREAD

**Issue by Charlie-George** [CGATOxford/CGATPipelines#249]
Transcript support level is only available from biomart for more recent versions - is there a different mapping for hg19 - do downstream pipeline rely on this - ( transcript diff expression for example ) make sure this is noted in the ini files of those pipelines also

**Comment by MikeDMorgan** [comment]
`downloadTranscriptSynonyms` also tries to access biomaRt with a specific set of column names which fails for older ensembl builds.  Also needs to be more flexible.
