### ISSUE TITLE
GENCODE tags in Ensembl GTF

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/CGATPipelines#256]
The Ensembl GTF includes some (not all) GENCODE [tags](https://www.gencodegenes.org/gencode_tags.html) which can be useful for defining a sensible reference transcriptome.

When the GTF is parsed by the annotation pipeline into the intial geneset_all.gtf.gz only one tag is retained. E.g

**Ensembl GTF**
`>zcat /ifs/mirror/ensembl/hg38/Homo_sapiens.GRCh38.82.gtf.gz|cut -f9|sed 's/;/\n/g' |grep tag |wc -l`
`3506997`

`zcat /ifs/mirror/ensembl/hg38/Homo_sapiens.GRCh38.82.gtf.gz|cut -f9|grep ENST00000335137| head -n1 | sed 's/; /\n/g'|grep tag`
`tag "CCDS"`
`tag "basic"`

**geneset_all**
`>zcat /ifs/mirror/ensembl/hg38/Homo_sapiens.GRCh38.82.gtf.gz|cut -f9|grep tag |wc -l`
`1994184`

`zcat ensembl.dir/geneset_all.gtf.gz|cut -f9|grep ENST00000335137| head -n1 | sed 's/; /\n/g'|grep tag`
`tag "basic"`

@AndreasHeger Any idea why this is happening? Presumably the tags are lost during the gff2gff.py step. I'll have a look into it. 

On a wider note, I wonder if we might be better off using the GENCODE annotations. The tags are a lot more informative that the information contained within the Ensembl GTF.

**Comment by Acribbs** [comment]
This issue is dealt with in the new pipeline_GTF_subset that I am writing.
