### ISSUE TITLE
Broken Relational Imports in CGATReports

### ISSUE THREAD

**Issue by jscaber** [CGATOxford/CGATPipelines#261]
Dear All,

following the py3 refactoring, CGATReports is no longer able to do the following relational imports:
`from .MappingReport import MappingTracker`

This can be easily fixed by getting rid of the `.` in front of the relational import.
Example of this can be found in Pull Request #260 . Thanks for @sebastian-luna-valero for the suggestion.

Any comments on whether this is a good way ahead are appreciated.
If ok, I will modify all known instances of this.

Best wishes,
Jakub

**Comment by AndreasHeger** [comment]
Thanks Jakub. Not sure why this is is now occurring (this is still py2.7, right?), but the solution looks good.

**Comment by jscaber** [comment]
Yes, just to confirm that I'm still running py2.7. I have no expanded the fixes to all CGATReports trackers.
Thank you!
