### ISSUE TITLE
pipeline_peakcallingScrum (Peakcalling-Scrum-2016): Missing parameters from the ini file

### ISSUE THREAD

**Issue by jaime11** [CGATOxford/CGATPipelines#296]
Hello,

Thank you for the updated pipeline_peakcallingScrum. I have been trying to run the pipeline_peakcallingScrum from the Peakcalling-Scrum-2016 branch, the attribute "filters_contigs_to_remove" seems to be missing from the pipeline.ini file.
Is there a more recent version of the pipeline.ini?

Thanks again!

**Comment by Charlie-George** [comment]
Oops sorry. I've just updated the ini file and pushed it. It might be a little rough in places - I'm just working on the reporting/stats for the filtering section and making so hopefully these updates will be pushed soon also. BW
