### ISSUE TITLE
Errors caused by change in job scripts

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#297]
Hi All,

we are in the process of moving over to a newer version of the repo and have a problem. 

Newer versions of Pipeline use `bash -e`. 

Now every script that is executed on our HPC comes back with error status 1, irrespective of the actual outcome of the job. I think this is because the `ulimit -v` call fails - users on our systems do not have permissions to alter the ulimit. Up till now this has not been a problem - `ulimit` returns an error, but the script carries on regardless and returns status 0 as long as the actual commands of interest succeed. But now this is no longer the case.

**Comment by sebastian-luna-valero** [comment]
Thanks @IanSudbery 

Could you please try the change proposed here:
https://github.com/CGATOxford/CGATPipelines/pull/298

and let me know if it works?

**Comment by sebastian-luna-valero** [comment]
@IanSudbery have you had the chance to test this?

I am planning to close this PR without merging by the end of this week if I have no feedback.
