### ISSUE TITLE
pipeline_testing not picking up certain files 

### ISSUE THREAD

**Issue by Charlie-George** [CGATOxford/CGATPipelines#301]
when setting up a test for pipeline_peakcallingScrum certain files are not being picked up by the suffixes 

for instance in pipeline_testing ini file I specify

`[test_peakcallingPEnarrow]
pipeline=pipeline_peakcallingScrum
suffixes=tsv,_filtered.bam,bed.gz,bed.gz,xls.gz,narrowPeak,filteringlog,idxstats`

the test_peakcallingPEnarrow.stats file lacks checksums for the "filteringlog" suffix despite the files existing (e.g. test_peakcallingPEnarrow.dir/filtered_bams.dir/mmATAC-KO-R3_filtered.filteringlog ) and the fact that other files in this directory have also been picked up

**Comment by sebastian-luna-valero** [comment]
Thanks @Charlie-George 

I will try to reproduce it and let you know.

**Comment by Acribbs** [comment]
I am also finding that some of my files are not being picked up.

Specifically the quant files.

for instance if I specify the following in the testing pipeline.ini
```[test_scrnaseqqc]
suffixes=quant,bam.stats,ercc.tsv.summary,fa,tsv,clean
```

**Comment by AndreasHeger** [comment]
Thanks, is it still an issue?

**Comment by sebastian-luna-valero** [comment]
Hello,

I was able to reproduce the error on the `Peakcalling-Scrum-2016` branch. The problem I found is with the `find` command in `buildCheckSums` function:
https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/pipeline_testing.py#L348

Particularly, with the `-not -regex ".*.log"` test, which is preventing the `filteringlog` files from being picked up.

@AndreasHeger we can:
* get rid of the `-not -regex ".*.log"` as we are using any way `-regex` with file extensions.
* require that file extensions do not contain the `log` substring.

What is your suggestion?

**Comment by AndreasHeger** [comment]
@sebastian-luna-valero , thanks, the ```-not -regex ".*.log"'``` can go.

**Comment by sebastian-luna-valero** [comment]
@AndreasHeger thanks, will try this https://github.com/CGATOxford/CGATPipelines/pull/305

**Comment by sebastian-luna-valero** [comment]
@Charlie-George @Acribbs 

Please merge your branches with the latest master and check whether this is still a problem.

**Comment by sebastian-luna-valero** [comment]
Solved with https://github.com/CGATOxford/CGATPipelines/pull/305
