### ISSUE TITLE
Duplicate files in pipeline_mapping.py when merging BAMs

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/CGATPipelines#32]
Currently, pipeline_mapping.py will merge BAMs from the same sample using the input and output patterns set in pipeline.ini

The Merged BAMs are then added to the global variable MAPPINGTARGETS on which the downstream functions are run. This duplicates the workload as all functions are run on all individual BAMs and the merged BAM. Presumably this is because the user may want to check the individual metrics of each unmerged BAM. However, if only the merged BAM is required this doubles the storage space and doubles the number of downstream tasks - for spliced mapping this includes rather lengthy quanitifcation steps. 

I propose that we add an option to the "merge" section of pipeline.ini to allow the user to request that the unmerged BAMs be removed (IOTools.zapFile) and the downstream tasks run only on the merged (MAPPINGTARGETS = mergeBAMFiles).

**Comment by AndreasHeger** [comment]
Thanks, to run all the downstream QC is part of the design.  The idea is to have the QC metrics both for the merged files, but also for the unmerged files. This is to spot if there have been any issues with particular lanes (for example, a higher proportion or unmapped reads). I think this is an important feature and suggest that all the metrics should be run on all BAM files.

We might need to look at the QC metrics and optimize their runtime, for example by only QCing a subsample, such as FastQC does. If 10% of the time in the pipeline is spent on mapping and the rest of QC we have got the balance wrong.

Adding a task to zap the unmerged BAM files is a good idea.
