### ISSUE TITLE
Annotations Pipeline Requirements

### ISSUE THREAD

**Issue by jscaber** [CGATOxford/CGATPipelines#320]
I have been working with the annotations pipeline with a GTF from elswhere and have noticed that the GTF that is provided has very specific requirements (I concatenated the GTF with the Ensembl GTF).

1. All entries from a gene_id have to be on the same strand [+/-]
2. Exons have to have unique exon_ids
3. The gtf has to be sorted first by gene_id and then by transcript_id

I wonder if sanity checks with sensible error messages and/or correction of the incompatibilities should be incorporated into the annotations pipeline.

**Comment by sebastian-luna-valero** [comment]
Hi @jscaber 

Would it be possible to add that to https://github.com/CGATOxford/CGATPipelines/pull/323?

**Comment by Acribbs** [comment]
I assume this was incorporated into the scrum. I will close but reopen if its still an issue
