### ISSUE TITLE
Picard Refflat Bugfix (pipeline_mapping.py)

### ISSUE THREAD

**Issue by jscaber** [CGATOxford/CGATPipelines#321]
I think I may have found the error that resulted in picard always reporting '0' coding reads in rnaseqmetrics.

The picard refflat in the mapping pipeline is generated from the cleaned up reference.gtf.gz.
This does not work, as the gtf contains information only on exons and not on cds and therefore no coding regions are marked in the flatfile. Cols 6 & 7 are always the same and identical to Col 5.
This can be fixed by using the geneset_all.gtf.gz from the annotations pipeline to build the flat gtf. I will generate a pull request.

**Comment by jscaber** [comment]
I have also added the same bugfix for pipline_rnaseqqc.py.

**Comment by sebastian-luna-valero** [comment]
Closed via https://github.com/CGATOxford/CGATPipelines/pull/322

Many thanks @jscaber !
