### ISSUE TITLE
import pandas.rpy.common as com

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/CGATPipelines#326]
Hello @CGATOxford/contributors 

The import tests on the master branch are failing on Travis:
https://travis-ci.org/CGATOxford/CGATPipelines/builds/228407995#L1499

After googling, this is due to a deprecated import in pandas `import pandas.rpy.common`:
http://pandas.pydata.org/pandas-docs/stable/r_interface.html

The affected pipelines are:
* RRBS
* TimeSeries

Could you please have a look at how to update this code, please? Instructions are on this link:
http://pandas.pydata.org/pandas-docs/stable/r_interface.html#rpy-updating

Many thanks,
Sebastian

**Comment by sebastian-luna-valero** [comment]
@MikeDMorgan many thanks for https://github.com/CGATOxford/CGATPipelines/pull/327

@TomSmithCGAT would you be able to have a look at the `pipeline_rrbs` and its corresponding module:
* https://travis-ci.org/CGATOxford/CGATPipelines/builds/229055628#L1499
* https://travis-ci.org/CGATOxford/CGATPipelines/builds/229055628#L1509

**Comment by TomSmithCGAT** [comment]
Hi @sebastian-luna-valero. I'll have a look at this shortly. Thanks for the pandas link for how to resolve this!

**Comment by TomSmithCGAT** [comment]
Done (#328)

**Comment by sebastian-luna-valero** [comment]
Brilliant, many thanks both!
