### ISSUE TITLE
3rd party dependencies in production pipelines

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/CGATPipelines#355]
I am creating conda environments for the production pipelines and wanted to ask whether the following dependencies are really required.

# Pipeline Annotations

## `map2slim`

Called in task `createGOSlim`:
- https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/pipeline_annotations.py#L2229
- https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/PipelineGO.py#L324

## `go2fmt.pl`

Called in task `buildGOPaths`:
- https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/pipeline_annotations.py#L2250
- https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/PipelineGO.py#L233

Also in task `buildGOTable`:
- https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/pipeline_annotations.py#L2258
- https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/PipelineGO.py#L252

# Pipeline Intervals

The following dependencies will be discarded in `pipeline_intervals.py` if no one objects:

- `BioProspector`
- `BroadPeak`

Please let me know your thoughts.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Hi All,

All the aforementioned dependencies will be ignored in the future conda environment for production pipelines.

Please reopen otherwise.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Update: I have packaged `go-perl` in bioconda (https://github.com/bioconda/bioconda-recipes/pull/7014) since `map2slim` and `go2fmt.pl` have been kept in the `pipeline_genesets` . The `go-perl` package will therefore be included in the conda environment during installation.

**Comment by Acribbs** [comment]
@sebastian-luna-valero What was Andreas opinion on removing the code from the pipeline?

**Comment by sebastian-luna-valero** [comment]
Thanks @Acribbs. Finally, I found and packaged the missing dependency so it wasn't necessary to remove the relevant code in the pipeline.

**Comment by Acribbs** [comment]
Brilliant! Thanks.
