### ISSUE TITLE
Python 2 dependencies in production code

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/CGATPipelines#369]
Following up on the GCProfile dependency, I wanted to mention that some of our production code still depends on python 2 software. At least I know of the following:
* `bx-python` in scripts
* `macs2`,  `sicer`, `tophat` in pipelines

Could any of these be removed as well? Or do we just need to work with python 2 environments to keep them?

**Comment by Acribbs** [comment]
Not sure about bx-python.

Currently macs2 isn't available for python 3 but looking at the GitHub repo it seems that they are working on porting it to python 3.

sicer isn't available for python 3 either and it looks like there is no effort in porting it to python 3. At the moment I find it useful for some of the very broad peak analysis, however I have seen this software that may do a better job and its not reliant on python. https://academic.oup.com/bioinformatics/article/29/4/492/199191. I will want to test it first, I also haven't seen the source code and I think it may have other dependancies. 

I think we could remove tophat as it only seems to be used for legacy work, but you would need to check with everyone to make sure no-one is using it.

**Comment by Charlie-George** [comment]
If possible can we leave tophat - there have been a couple of cases where I've wanted to double check workflows of public data and used it to double check their analysis against mine - I guess those cases become less and less but it's easier to keep something in rather then have to add it again.

**Comment by Acribbs** [comment]
Ok Tophat can stay, do you have any experience running the python 3 branch for macs2?

**Comment by Charlie-George** [comment]
Thanks :). Yes the py3 branch for macs2 should be fine - the location of the python 2 macs2 env is in the ini - it just appends this to the begining of the statement and it should just work, at least it was when I used it a couple of months ago. I tested it throughly in both enviroments py3 and py2 and it was fine and made tests for all possible routes of macs2/IDR although you have to run them locally as not all of the env are tested automatically.  IDR also has it's own seperate py3 env because the IDR version in conda wasn't upto date and had a bug in it and we had to go through a convoluted install procedure, hence we made a seperate py3 env for the IDR. I think this is all documented on the wiki/within the pipeline.

**Comment by Acribbs** [comment]
@sebastian-luna-valero what is the decision for moving forward with this issue? It seems like macs2 and tophat will need to stay for the time being.

**Comment by sebastian-luna-valero** [comment]
Hi,

Thanks for your replies and sorry for my silence. 

Right now we use a central conda environment for py2 dependencies but this is not portable. My plan is update the installation so the py2 environment is created with the installation of the code and therefore will be moved outside as well.

I will create a pull request.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Update: this will only be valid for command-line tools like `tophat`, `macs2` and hopefully `sicer` (which I remember was tricky to install). Regarding `bx-python`, we will still use the `pip install` until we find a way forward (either it is ported to python 3, or we refactor our code to remove the dependency)

**Comment by sebastian-luna-valero** [comment]
Following up on Lior's tweet (thanks @Acribbs for forwarding):
https://twitter.com/lpachter/status/937055346987712512

Do we still want to include `tophat` in our py2 environment?

**Comment by IanSudbery** [comment]
I guess yes. We still need to be able to reproduce published results.

**Comment by TomSmithCGAT** [comment]
I'm with Ian. I can't see any justification for using Tophat for our own analyses but it is useful for reproducing other people's work, especially seen as it's still so popular 😱

**Comment by Acribbs** [comment]
I think a lot of the popularity is just wrong citation, I think the majority of work is on Tophat2/hisat2 but people keep citing wrong paper, well thats my feeling anyway

**Comment by TomSmithCGAT** [comment]
Very possibly true. I hope so!

**Comment by sebastian-luna-valero** [comment]
Following up on this, in https://github.com/CGATOxford/CGATPipelines/pull/381 I try to solve this issue.  Please note that there will be better ways of solving the problem and we can implement them in new pipelines. For the time being, this seems to work for the existing code. Any proposal/feedback is more than welcome.
