### ISSUE TITLE
fastq naming convention

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/CGATPipelines#388]
Commonly used naming convention for pair-end reads is `.1.fastq.gz` and `.2.fastq.gz` whereas the CGAT convention is `.fastq.1.gz` and `.fastq.2.gz`

Our pipelines needs to support both. Right now we need to fix:
* mapping
* readqc

**Comment by MikeDMorgan** [comment]
I don't think there is actually a proper convention.  Generally speaking I think that should be part of the file name mapping step, i.e. we often want to change from the (somewhat) arbitrary and obfuscated filenames from the sequencing centre, to something more meaningful, e.g. <tissue>-<condition>-<replicate>.  This also means that any convention used by the sequencing centre for determining paired end files can also be change.  All of this is achievable with cgat_tsv2links.py.  Therefore it lies outside of the pipelines?

**Comment by Charlie-George** [comment]
all my illumina reads come in the format Blah_Blah_Lane_R1.fastq.gz, Blah_Blah_Lane_R2.fastq.gz  for reads 1 and 2 so users would still have to rename them to 1.fastq.gz and 2.fastq.gz anyway? if your doing that you might as well rename it to fastq.1.gz fastq.2.gz.

**Comment by sebastian-luna-valero** [comment]
@david-cgat please let us know your thoughts

**Comment by AndreasHeger** [comment]
This will be a difficult change, as the distinction between fastq.gz and fastq.1.gz is used to correctly process both single-end and paired-end data based on their suffix. If .fastq.gz is a common suffix, the pipelines will need major refactoring.

**Comment by sebastian-luna-valero** [comment]
Thanks All!

Probably we just need to highlight in the documentation/tutorials that `cgat_tsvlinks.py` has to be used if the provided input files are not in the format expected by the pipelines. I am happy to help if someone points me into the right direction.
