### ISSUE TITLE
pipeline_annotations pep8 error

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/CGATPipelines#40]
Dear All,

I have just fixed a problem with the installation script of the CGATPipelines (thanks @jscaber!).

However, the master branch of the CGATPipelines is failing due to a pep8 error:
https://travis-ci.org/CGATOxford/CGATPipelines/jobs/67868390#L1790

Could you please have a look?

Many thanks,
Sebastian.

**Comment by jscaber** [comment]
Fixed & sent pull request.
Jakub
