### ISSUE TITLE
Reference genome "*.fasta" in addition to ".fa"

### ISSUE THREAD

**Issue by kevinrue** [CGATOxford/CGATPipelines#407]
https://github.com/CGATOxford/CGATPipelines/blob/48eba7d41297a268a622a4e5d98a5a5565af52be/CGATPipelines/PipelineMapping.py#L368

Could reference genomes be supported with both "fa" and "fasta" extensions? Or is there a particular reason/pipeline that should be used to ensure only "fa" are supported here?

Thanks!

**Comment by Acribbs** [comment]
I assume that this was because the UCSC convention is to name the fasta files of the reference genome .fa. @AndreasHeger can probably shed more light.

**Comment by kevinrue** [comment]
Nevermind, I need to learn how to read comments in `pipeline.ini`:
```
# location of indexed genome, needs to be set
genome_dir=/gfs/mirror/genomes/plain # <<<< should have been /gfs/mirror/genomes/index in my case
```

Sorry for the waste of time -_-
