### ISSUE TITLE
pipeline_mapping.py uploads duplicated read counts when mergeReadCounts is not performed

### ISSUE THREAD

**Issue by nickilott** [CGATOxford/CGATPipelines#419]
Hi,

When there is no pattern set for counting reads (mergeReadCounts) and the dummy task is used pipeline_mapping.py takes read counts twice for each file i.e.

@merge((countReads, mergeReadCounts), "reads_summary.load")
def loadReadCounts(infiles, outfile):
...

The two infiles here have the same output when counts aren't merged. I have fixed this by adding:

infiles = set(infiles)

so that only unique files are uploaded to the database. I will submit a pull request for this.

Nick

**Comment by sebastian-luna-valero** [comment]
Thanks, Nick.

Fixed with https://github.com/CGATOxford/CGATPipelines/pull/420
