### ISSUE TITLE
Unknown resource 'picard'

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#42]
I'm getting this error trying to run pipeline_mapping. 

The picard resource was defined on the CGAT cluster, because running multiple picard jobs on a single compute node was leading to some very odd states where the processes would effectively wait forever, thus the picard resource was defined to allow only on process to run at once.

However, I'm not able to define this resorce on the cluster here. How might I get around this problem? I could just rip out the code referring to the picard resource, but I don't know if that is going to lead to problems.

**Comment by AndreasHeger** [comment]
Thanks. I think we need to get rid of this resource requirement and put in place a mechanism to specify job parameters for given jobs in pipeline.ini. I can implement that. 

In the meantime if you want to submit a pull-request without all the picard requirements, please do so. I almost expect that this problem has gone away with upgrades to java and picard.

**Comment by IanSudbery** [comment]
See above PR
