### ISSUE TITLE
pipeline_peakcalling matplotlib.pyplot `.figure` error

### ISSUE THREAD

**Issue by kevinrue** [CGATOxford/CGATPipelines#427]
https://github.com/CGATOxford/CGATPipelines/blob/46f38403040471c7a5972a0db70381959833743f/CGATPipelines/pipeline_peakcalling.py#L1576

Running into the issue `_tkinter.TclError: couldn't connect to display "localhost:11.0"`
Following https://stackoverflow.com/questions/44517289/matplotlib-graph-not-showing, I've tried adding:
```
import matplotlib
matplotlib.use('agg') # or also matplotlib.use('Agg')
```
but I still get the same error.
Any idea?

**Comment by AndreasHeger** [comment]
Hi Kevin,

set in your matplotlibrc config file your backend to agg. This is what I 
usually do if I work remotely.

https://matplotlib.org/users/customizing.html#the-matplotlibrc-file

Avoid adding matplotlib.use() statements into code. They often don't 
work as the import order is important and are executed even when only 
importing a module. Better rely on the user for configuration.

Best wishes,
Andreas

**Comment by kevinrue** [comment]
Thanks, it works now!
For the record, I've created the file `~/.config/matplotlib/matplotlibrc` that didn't exist yet (the folder did exist)
And for only content,  I've added the line
```
backend      : Agg
```
