### ISSUE TITLE
Specifying job_memory for cluster_runnable decorated jobs

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/CGATPipelines#45]
When Ian wrote the cluster_runnable decorator in Pipeline.py, we were specifying the memory required for each job using e.g jobOptions="-l mem_free=2G", then job_options="-l mem_free=2G". 

We're now using the variable job_memory. Unless I'm mistaken, the decorator does not recognise job_memory as a submit argument when pickling the arguments with Pipeline._pickle_args(). I've added "job_memory" and "job_threads" to the list of arguments which should be used as submit arguments and added empty strings for the arguments to Pipeline.submit() (TS-working branch). Is this the right approach?

**Comment by AndreasHeger** [comment]
Yes, that is correct. Thanks!

**Comment by IanSudbery** [comment]
Thanks Tom. I similar thing probably needs to happen with job_threads as well, although less urgent, as I suspect few jobs using this mechanism require more than one thread.

**Comment by TomSmithCGAT** [comment]
@IanSudbery I included job_threads as well (defaulted to 1), though I agree this is unlikely to ever be needed.

**Comment by AndreasHeger** [comment]
Thanks, can this issue be closed?

**Comment by TomSmithCGAT** [comment]
yes, thanks

Dr Tom Smith
CGAT Training Fellow | http://www.cgat.org
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
