### ISSUE TITLE
lincRNAs in pipeline_annotations

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#52]
All annotation for lincRNA transcripts is currently missing in the pipeline_annotations transcript_info table. This is because when `downloadTranscriptInfomation` queries biomart it asks for the uniprot_id. Of course lincRNAs don't have a uniprot id. In other cases where information is missing, biomart just returns an empty field (it appears to be doing a LEFT JOIN), but in the case of uniprot, the whole record is lost (it appears to be doing an INNER JOIN). This is somewhat of a problem for any work with lincRNAs at the transcript level (gene_ids are present). 

Does anyone actaully use the uniprot ids? Could they be removed?

**Comment by AndreasHeger** [comment]
Yes, uniprot ids could be removed. They should go into a separate table.

Best,
Andreas

**Comment by AndreasHeger** [comment]
(The polyphen pipeline was making use the uniprot ids, but this part is currently dormant)

**Comment by AndreasHeger** [comment]
done, see 81e752e7c0b1fd790270d430c5da07bd6d5145a5
