### ISSUE TITLE
Database access from CGATReport

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#54]
Thanks for sorting out the database moving. One last thing that needs to move, and I need suggestions as to how to do it...

Some of the pipeline report trackers read their database location from pipeline specific sections of the ini file. For example, from MappingReport.py:

```
DATABASE = P.get('mapping_backend', P.get('sql_backend', 'sqlite:///./csvdb')
```

However, the database stuff is now in `[database]` rather than `[general]` or `[mapping]`. If this were changed to `[database]` however, it would be difficult to do the whole using trackers from other pipelines business.

Ian

**Comment by AndreasHeger** [comment]
Thanks. I agree that would be tricky. Is this a feature that you use often? 

Best wishes,
Andreas

**Comment by IanSudbery** [comment]
Yeah, fairly often, to build interpretive meta-reports, or to refer to information from production reports in project pipelines. I've been getting around it so far by replicating the information from [database] in [mapping].

**Comment by AndreasHeger** [comment]
@IanSudbery, the solution you have found is the best. Basically, for linked reports, we should use
the "mapping_backend". What needs to change is how to get the the other defaults. The sequence
should probably be:

```
DATABASE = P.get('mapping_backend', P.get('database_backend', P.get('sql_backend', 'sqlite:///./csvdb'))
```

This is cumbersome and there might be away to wrap this. 

A short-coming of the whole mechanism is that you can only have one database for a particular
tracker. This will cause problems if you want to compare things like two mapping pipelines in tables side-by-side. 

Probably the most generic solution is to be able to provide a database argument for a tracker. I will  continue to look into this.

**Comment by AndreasHeger** [comment]
Hi @IanSudbery , new mechanism is outlined [here](https://www.cgat.org/downloads/public/CGATReport/documentation/Advanced.html#using-macros-from-another-cgatreport-document). For example:

```
.. report:: pipeline_docs.pipeline_mapping.trackers.MappingSummary
   :render: table
   :sql_backend: sqlite:///../mapping_sensitive/csvdb

   Mapping summary using sensitive mapping parameters

.. report:: pipeline_docs.pipeline_mapping.trackers.MappingSummary
   :render: table
   :sql_backend: sqlite:///../mapping_strict/csvdb

   Mapping summary using strict mapping parameters
```

I have not managed to fully tested this, will revisit once I am back from leave.

Best wishes,
Andreas

**Comment by Acribbs** [comment]
@IanSudbery can this issue be closed?

**Comment by Acribbs** [comment]
Closed, but please reopen if necessary
