### ISSUE TITLE
rpy2 version

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/CGATPipelines#55]
Hi all,

There is now a conflict between rpy2 and r-3.2. That is why the master is failing to run the import tests successfully:
https://travis-ci.org/CGATOxford/CGATPipelines/jobs/69439799#L1830
https://travis-ci.org/CGATOxford/CGATPipelines/jobs/69439799#L1840

Specifically, it seems to be a problem of how rpy2 is imported. Please see:
https://bitbucket.org/rpy2/rpy2/issue/274/name-conversion-rule-when-there-is-a-dot#comment-17983466
https://bitbucket.org/rpy2/rpy2/issue/277/suppress-importr-exceptions-behind

Although the link above points to a fix for rpy2-2.6 and we are still using rpy2-2.4. Is there a reason to keep using rpy2-2.4 instead of the latest version?

Best regards,
Sebastian.

**Comment by AndreasHeger** [comment]
There used to be an issue, but I think we should try again with the latest version.

**Comment by sebastian-luna-valero** [comment]
I have updated the installation script so the latest version of rpy2 is installed for the development version of the code but not on the production version of the scripts.

Tests are passing on both repositories, so will close this.

Many thanks,
Sebastian.
