### ISSUE TITLE
Memory usage in Pipeline.load

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#62]
I am finding that some of my csv2db commands, issued through Pipeline.load are running out of memory. For example, in pipeline_rnaseqtranscripts, the _transcripts tables can be very big, and the loading process memory intensive. However, as they are run through Pipeline.load, there is no mechanism for specifying job_memory.

**Comment by AndreasHeger** [comment]
Thanks, loading the should not (but is) a memory intensive option. Currently, the default is to use multi-insert statements. Better is to use --quick option. However, this has so far only been implemented for sqlite3, and it might also not be done in the most portable way (you need sqlite3 in your path, for example).

**Comment by IanSudbery** [comment]
Is this a short term or long term thinking? Is there something we can do in the short-term? Perhaps allow a `job_memory` to be passed to P.load? I suppose ideally the length of the file would be tested and the memory required calculated appropriately, but thats probably too much for right now.

**Comment by AndreasHeger** [comment]
I think it could be done short-term. I will try what changing the default will do to our pipelines.

Best wishes,
Andreas

**Comment by IanSudbery** [comment]
So I added a check for backend="csvdb" and if true added "--quick". Any reason why this might not work?

**Comment by IanSudbery** [comment]
When I use "--quick", csv2db.py get stuck in an infinite loop with the error:

```
2015-08-05 15:04:42,966 WARNING import error using statement: sqlite3 -header -csv -separator ' ' csvdb '.import /tmp/2967429.1.all.q/tmpiuQd9B chunk_counts'
```

I added code to find out what the error is, but the retcode is 1, which is just SQLITE_ERROR.

**Comment by AndreasHeger** [comment]
Thanks, fixed this. There was a problem with the column separator.

Currently the method always dumps the whole table before inserting with quick in order to strip comments or if input comes from stdin. Thus --quick for small tables might actually be slower.

Probably best to set it on demand.

**Comment by Acribbs** [comment]
@IanSudbery can this be closed?

**Comment by IanSudbery** [comment]
I guess so, yes.
