### ISSUE TITLE
Sphinx ZeroDivisionError in mapping pipeline report

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#73]
Hi Guys,
I'm failing to be able to build the mapping report. I get a few of the pages, but not many, and they are not formatted, it looks like the css is missing. Checking in report.log I find the following:

```
writing output... [  6%] contents
writing output... [ 13%] pipeline
writing output... [ 20%] pipeline/Geneprofiles
writing output... [ 26%] pipeline/Mapping
writing output... [ 33%] pipeline/MappingAlignmentStatistics
writing output... [ 40%] pipeline/MappingComplexity
writing output... [ 46%] pipeline/MappingContext

Exception occurred:
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/docutils/writers/html4css1/__init__.py", line 644, in write_colspecs
    colwidth = int(node['colwidth'] * 100.0 / width + 0.5)
ZeroDivisionError: float division by zero
```

I've no idea whats going on here. Worked fine until recently.

**Comment by AndreasHeger** [comment]
There is an issue with tables of more than ~100 columns. I have changed CGATReport to automatilly
make tables with more than 100 columns external. Do you use your own CGATReport or the shared one?

**Comment by IanSudbery** [comment]
Bingo. Thanks.

**Comment by AndreasHeger** [comment]
Thanks, closing this.
