### ISSUE TITLE
pairs_proper_unique_alignments in mapping report

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#74]
The mapping pipeline report is trying to find the pairs_proper_unique_alignments column in view_mapping, but there is no such column in the table, nor is it output by bam2stats (i'm pretty such I have the latest version).

**Comment by AndreasHeger** [comment]
thanks, fixed in 1adee5050fc5cb878cdf13c1c129c44ab3c48171, just pushing the changes.
