### ISSUE TITLE
Error on single end mapping report

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#75]
The Status tracker of the mapping report tries to report on the % of pairs mapped. However, if the samples were single ended, there is no pairs_proper_unique in the view_mapping table, and an error is returned.

The code uses self.getValue to get the results, and then checks if value is None. Presumably once upon a time the column was present, but contained NA if if the samples were not paired, but not anymore.

**Comment by AndreasHeger** [comment]
Thanks, I will check.

**Comment by AndreasHeger** [comment]
Fixed, exception is now caught if there is only single end data.
