### ISSUE TITLE
pipeline_rnaseqtranscripts - nexperiments 

### ISSUE THREAD

**Issue by Charlie-George** [CGATOxford/CGATPipelines#76]
In the buildPrunedGeneSet function  "nexperiments > 1" is used to filter the ab-initio gene set generated by cuffcompare for transfrags "that occur in at least two samples across all of the experiments to remove partial transfrags that are the result of low coverage observations in one sample". 

However the nexperiment values (calculated in buildAndLoadFullGeneSetTracking) does not strictly give the number of samples that the transfrag is identified in (I have 18 samples but i'm getting transcripts that have an nexperiment value of up to 288), rather it calculates the number of other transcripts that the transfrag is found in across all the samples. For instance the transfrag may be identified in three different transcripts all from sample X. The nexperiments value is then 3, despite this transcript only being in one sample.    

This can be fixed by using a regular expression to filter for the sample id ... but should I do this, or do we want to keep transfrags that are in more then one transcript rather then more then one sample? I'm inclined to go for the former, but opinions would be appreciated?

**Comment by TomSmithCGAT** [comment]
Well spotted! I think we should be filtering on the number of samples in which the transfrag is observed which is what the pipeline is intending to do, e.g. we should filter on the sample_id also.
