### ISSUE TITLE
pipeline_peakcalling - add regression tests

### ISSUE THREAD

**Issue by AndreasHeger** [CGATOxford/CGATPipelines#8]

**Comment by TomSmithCGAT** [comment]
@Charlie-George I've set up a new branch to work on pipeline_peakcalling (TSCG-scrumAPR
Once you've split the scripts and pipelines, if you go to your new CGATPipelines repository and run 

`git fetch`

You should see the line:

_[new branch]      TSCG-scrumAPR15_pipeline_peakcalling -> origin/TSCG-scrumAPR15_pipeline_peakcalling"_

which tells you that you have a new local branch available which tracks the remote branch ("origin/TSCG-scrumAPR15_pipeline_peakcalling")

Next, run the following command to checkout the branch

`git checkout TSCG-scrumAPR15_pipeline_peakcalling`

If you need to change onto another branch, for example if you wanted to return to master, use

' git checkout master'

You can return to the pipeline_peakcalling scrum branch at anytime by using the above `git checkout` command again. When we start making changes to our individual local repositories we'll need to push them to the remote repository using the usual `git add`, `git commit -m "some explanation here"` and `git push` commands. The other person can pull them with `git pull`. Once we're happy that we've finished off the changes to the pipeline we'll push the final changes and issue a git merge request via github to Andreas. 

I've set up a directory from which we can perform the initial testing of the pipeline at _/ifs/devel/toms/pipeline_peakcalling_ which you should be able to use too. There's a subdirectory called _"check_functional"_ which we can use to do some initial work to check the pipeline is functional and other subdirectories for testing later. I'll find some suitable data shortly and place it in _"check_functional"_ so we can start making sure the pipeline runs correctly

**Comment by Charlie-George** [comment]
I've updated the pipeline with minor changes that should let it run and I'll raise issues for the other things that need to be done.

**Comment by TomSmithCGAT** [comment]
@Charlie-George I've had to move the directory for testing pipeline_peakcalling to _/ifs/projects/toms/pipeline_peakcalling/_ as I ran out of space in my devel directory.

**Comment by TomSmithCGAT** [comment]
@Charlie-George Regression tests for pipeline peakcalling have been added to the pipeline.ini for pipeline_testing.py
