### ISSUE TITLE
Unexplained test failure on branch

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#84]
@sebastian-luna-valero I wonder if you could help me out. My branch at 775b8eb passes tests on my local machine, but is failing the import tests on Travis, I can't work out why.

**Comment by sebastian-luna-valero** [comment]
It fails locally for me as well when I run nosetests:

```
AssertionError: pipeline_rnaseqtranscripts scripts/modules - Exception:     

    @jobs_limit(db, "10") cannot re-defined with a different limit of 1
```

but I am not sure what is going on here, as the error differs from Travis.

However, it does not complain when I import the code directly from python.

```
python -c "import CGATPipelines.pipeline_rnaseqtranscripts"
```

**Comment by AndreasHeger** [comment]
Hi both,

the only jobs_limit in pipeline_rnaseqtranscripts I see is:

``` python
@jobs_limit(PARAMS.get("jobs_limit_R", 1), "R"
```

The error might be somewhere else?

**Comment by IanSudbery** [comment]
The reason for this is that I had set a db limit of 1 in my `.cgat`

The gulty line should not be hardcoding a job limit of "10" but fetching it from the PARAMS. Now fixed.
