### ISSUE TITLE
Attributes have different names in different biomart

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#85]
Hi All,

The annotations pipeline downloads transcript information from biomart. When building from archived marts some of the attributes have different names than they do in the current marts. For example, the attribute `external_transcript_name`, used for fetching information for the transcript pseudonyms table is spelt `external_transcript_id` in the archives.

**Comment by jaime11** [comment]
Hello,

I am also having this problem too:

R
library(biomaRt)
mart = useMart(biomart="ENSEMBL_MART_ENSEMBL", host="www.ensembl.org", dataset="mmusculus_gene_ensembl")
listAttributes(mart)[grep("external",listAttributes(mart)$name),]
                                name                  description
18                external_gene_name         Associated Gene Name
19              external_gene_source       Associated Gene Source
20          external_transcript_name   Associated Transcript Name
21   external_transcript_source_name Associated Transcript Source
34                 study_external_id     Study External Reference
184               external_gene_name         Associated Gene Name
185             external_gene_source       Associated Gene Source
214               external_gene_name         Associated Gene Name
215             external_gene_source       Associated Gene Source
1080              external_gene_name         Associated Gene Name
1081            external_gene_source       Associated Gene Source
1117              external_gene_name         Associated Gene Name
1118            external_gene_source       Associated Gene Source
1138              external_gene_name         Associated Gene Name
1139            external_gene_source       Associated Gene Source

mart = useMart(biomart="ENSEMBL_MART_ENSEMBL", host="may2012.archive.ensembl.org", dataset="mmusculus_gene_ensembl")
listAttributes(mart)[grep("external",listAttributes(mart)$name),]
                       name                description
13         external_gene_id       Associated Gene Name
14   external_transcript_id Associated Transcript Name
15         external_gene_db         Associated Gene DB
123        external_gene_id       Associated Gene Name
124        external_gene_db         Associated Gene DB
163        external_gene_id       Associated Gene Name
164        external_gene_db         Associated Gene DB
1538       external_gene_id       Associated Gene Name
1539       external_gene_db         Associated Gene DB
1545            external_id               Reference ID
1578       external_gene_id       Associated Gene Name
1579       external_gene_db         Associated Gene DB

Thank you.

Kind regards.

**Comment by Acribbs** [comment]
Closed because this should be handled properly in new pipeline when it is released. Please reopen if issue still persists in new release
