### ISSUE TITLE
Moving reports to new locations

### ISSUE THREAD

**Issue by katherinef** [CGATOxford/CGATPipelines#92]
Dear all,

I have a password protected folder in my web folder for publishing sensitive information for collaborators.  However, I can't publish directly to this folder using CGAT pipelines and instead I publish as normal then copy and paste the report to the secure folder.  The issue is that when I delete the original report in the non-secure web folder the report in the secure folder no longer works so it looks like there is a link being created.  Does anyone know how to resolve this?

Many thanks

Kath

**Comment by AndreasHeger** [comment]
Hi Kath,

publishing a report entails changing the URLs. This is currently implemented with absolute paths, but should better be done with relative paths.

I will look into this.

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Hi Kath,

can you tell me exactly what does not work? Is it excel spreadsheets?

Best wishes,
Andreas
