### ISSUE TITLE
Database configuration in ini files

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#96]
Hi Guys,

We have moved the location where the database name is specified so that we now specify it:

```
[database]
name=csvdb
```

but all of the standard pipeline.ini files still specify it

```
[general]
database=csvdb
```

The standard ini's need to be updated. I can do it something, but I'm really busy teaching for the next couple of weeks.

**Comment by TomSmithCGAT** [comment]
Hi Ian,

We've got a scrum on Monday/Tuesday so we can sort this then. 

Cheers

**Comment by AndreasHeger** [comment]
I have removed all these statements.

**Comment by IanSudbery** [comment]
Erm, shouldn't the ini files contain a 

```
[database]
name=csvdb
```

section?
